# Ex - GroupBy

### Introduction:

GroupBy can be summarized as Split-Apply-Combine.

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

Check out this [Diagram](http://i.imgur.com/yjNkiwL.png)  
### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv).

In [6]:
data = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv', sep=',')

### Step 3. Assign it to a variable called drinks.

In [8]:
drinks = pd.DataFrame(data)

### Step 4. Which continent drinks more beer on average?

In [9]:
drinks.groupby('continent').beer_servings.mean()

continent
AF     61.471698
AS     37.045455
EU    193.777778
OC     89.687500
SA    175.083333
Name: beer_servings, dtype: float64

### Step 5. For each continent print the statistics for wine consumption.

In [10]:
drinks.groupby('continent').wine_servings.describe()

           count        mean        std  min   25%    50%     75%    max
continent
AF          53.0   16.264151  38.846419  0.0   1.0    2.0   13.00  233.0
AS          44.0    9.068182  21.667034  0.0   0.0    1.0    8.00  123.0
EU          45.0  142.222222  97.421738  0.0  59.0  128.0  195.00  370.0
OC          16.0   35.625000  64.555790  0.0   1.0    8.5   23.25  212.0
SA          12.0   62.416667  88.620189  1.0   3.0   12.0   98.50  221.0

### Step 6. Print the mean alcohol consumption per continent for every column

In [12]:
drinks.groupby('continent').total_litres_of_pure_alcohol.mean()

continent
AF    3.007547
AS    2.170455
EU    8.617778
OC    3.381250
SA    6.308333
Name: total_litres_of_pure_alcohol, dtype: float64

### Step 7. Print the median alcohol consumption per continent for every column

In [13]:
drinks.groupby('continent').total_litres_of_pure_alcohol.median()

continent
AF     2.30
AS     1.20
EU    10.00
OC     1.75
SA     6.85
Name: total_litres_of_pure_alcohol, dtype: float64

### Step 8. Print the mean, min and max values for spirit consumption.
#### This time output a DataFrame

In [15]:
drinks.groupby('continent').spirit_servings.agg(['mean', 'min', 'max', 'sum'])

                 mean  min  max   sum
continent
AF          16.339623    0  152   866
AS          60.840909    0  326  2677
EU         132.555556    0  373  5965
OC          58.437500    0  254   935
SA         114.750000   25  302  1377