# US - Baby Names

### Introduction:

We are going to use a subset of [US Baby Names](https://www.kaggle.com/kaggle/us-baby-names) from Kaggle.  
In the file it will be names from 2004 until 2014


### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv).

In [8]:
from pathlib import Path

csv_path = Path.cwd() / "06" / "Stats" / "US_Baby_Names" / "US_Baby_Names_right.csv"

if not csv_path.exists():
    csv_path = Path.cwd() / "US_Baby_Names_right.csv"

dataset = pd.read_csv(csv_path)

### Step 3. Assign it to a variable called baby_names.

In [20]:
baby_names = dataset.copy()

### Step 4. See the first 10 entries

In [21]:
baby_names.head(10)

   Unnamed: 0     Id      Name  Year Gender State  Count
0       11349  11350      Emma  2004      F    AK     62
1       11350  11351   Madison  2004      F    AK     48
2       11351  11352    Hannah  2004      F    AK     46
3       11352  11353     Grace  2004      F    AK     44
4       11353  11354     Emily  2004      F    AK     41
5       11354  11355   Abigail  2004      F    AK     37
6       11355  11356    Olivia  2004      F    AK     33
7       11356  11357  Isabella  2004      F    AK     30
8       11357  11358    Alyssa  2004      F    AK     29
9       11358  11359    Sophia  2004      F    AK     28

### Step 5. Delete the column 'Unnamed: 0' and 'Id'

In [22]:
baby_names.drop(columns=['Unnamed: 0', 'Id'], inplace=True)

### Step 6. What year has the highest number of baby names in the dataset?

In [23]:
baby_names.groupby(by='Year')['Count'].sum().idxmax()

np.int64(2007)

### Step 7. Is there more male or female names in the dataset?

In [24]:
baby_names.groupby(by='Gender')["Count"].sum()

Gender
F    16380293
M    19041199
Name: Count, dtype: int64

### Step 8. Group the dataset by name and assign to names

In [35]:
names = baby_names.groupby(by='Name').sum()
names

,Year,Gender,State,Count
Name,,,,
Aaban,4027,MM,NYNY,12
Aadan,8039,MMMM,CACACATX,23
Aadarsh,2009,M,IL,5
Aaden,393963,MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM...,ALALALALALALALARARARAZAZAZAZAZAZCACACACACACACA...,3426
Aadhav,2014,M,CA,6
...,...,...,...,...
Zyra,14085,FFFFFFF,CACACAFLTXTXTX,42
Zyrah,4024,FF,CATX,11
Zyren,2013,M,TX,6
Zyria,20089,FFFFFFFFFF,GAGAGALALALATXTXTXTX,59
Zyriah,18087,FFFFFFFFF,GAGALATXTXTXTXTXTX,58

### Step 9. How many different names exist in the dataset?

In [37]:
names.shape

(17632, 4)

### Step 10. What is the name with most occurrences?

In [39]:
names.Count.idxmax()

'Jacob'

### Step 11. How many different names have the least occurrences?

In [45]:
min_occur = names[names.Count == names.Count.min()]

In [46]:
min_occur.shape

(2578, 4)

### Step 12. What is the median name occurrence?

In [48]:
median_occur = names[names.Count == names.Count.median()]
median_occur

          Year    Gender             State  Count
Name
Aishani  14078   FFFFFFF    CACACACACAILNJ     49
Alara    16079  FFFFFFFF  CACACAFLNYNYNYTX     49
Alysse   16057  FFFFFFFF  CACACAMINYTXTXTX     49
Ameir    16086  MMMMMMMM  CAMIMIMIMIMINYOH     49
Anely    16071  FFFFFFFF  CACACACACACACACA     49
...        ...       ...               ...    ...
Sriram   14054   MMMMMMM    CACACACACACATX     49
Trinton  16069  MMMMMMMM  FLLAOKTXTXTXTXTX     49
Vita     14075   FFFFFFF    CACACACACANYNY     49
Yoni     16060  MMMMMMMM  CACACACACACAFLFL     49
Zuleima  14050   FFFFFFF    AZCACACACACACA     49

[66 rows x 4 columns]

### Step 13. What is the standard deviation of names?

In [52]:
names.Count.describe()

count     17632.000000
mean       2008.932169
std       11006.069468
min           5.000000
25%          11.000000
50%          49.000000
75%         337.000000
max      242874.000000
Name: Count, dtype: float64

### Step 14. Get a summary with the mean, min, max, std and quartiles.